//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petshop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ItemId { get; set; }
        public int OrderId { get; set; }
        public string ProName { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
